### ISSUE TITLE
Different html font-size between Dev and SSR

### ISSUE THREAD

**Issue by andrewspy** [nuxt-community/vuetify-module#106]
**Module version**
1.2.1

**Describe the bug**
With Dev (i.e. `yarn dev`), `main.sass` style `html` as:

```css
html {
  font-size: 16px;
  overflow-x: hidden;
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
}
```

With SSR (i.e. `nuxt.render(req, res)`), rendered page style `html` as:

```css
html {
  font-size: 20px;
  overflow-x: hidden;
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  -webkit-tap-highlight-color: rgba(0,0,0,0)
}
```

**To Reproduce**

Using `create-nuxt-app` with vuetify template, and the SSR is at:
https://x-nuxt-app.web.app/

**Expected behavior**
html font size should be the same.

**Screenshots**
![nuxt-vuetify-dev](https://user-images.githubusercontent.com/3106425/62650270-10801b80-b989-11e9-8ac7-6f48ce7bb536.jpg)

**Additional context**
I'm new to nuxt, and not 100% sure if I deploy nuxt SSR correctly to firebase cloud functions...
