### ISSUE TITLE
How to override vuetify styles

### ISSUE THREAD

**Issue by altynbek07** [nuxt-community/vuetify-module#309]
**Module version**
@nuxtjs/vuetify@1.11.0

**Describe the bug**
I want to overwrite default vuetify styles (not variables) with my custom styles. But vuetify styles is overwritten with custom styles.

**To Reproduce**
For example:
In file `nuxt.config.js`:
```js
...
css: [
    '~assets/scss/style.scss'
],
...
buildModules: [
    ['@nuxtjs/vuetify',
      {
        /*
        ** some options
        */
      }
    ],
]
```
In file `assets/scss/style.scss`:
```css
.container {
	padding-top:0;
	padding-bottom: 0;
	padding-right: 15px;
	padding-left: 15px;
	margin-right: auto;
	margin-left: auto
}
```
**Expected behavior**
I have a lot of files where I redefine styles and so I want my `.container` class styles to apply. Is there any correct way to prioritize my class files?

**Additional context**
default `.container` class styles:
```css
.container {
    width: 100%;
    padding: 12px;
    margin-right: auto;
    margin-left: auto;
}
```

**Screenshots**
<img width="328" alt="atyrauprint-front 2020-04-17 19-36-18" src="https://user-images.githubusercontent.com/20629188/79580842-0d762700-80e3-11ea-897f-9e3c1a77772a.png">

**Comment by marcpaskell** [comment]
Try importing them via a plugin in nuxt.config

~/plugins/vendor/vuetify'
```
import '~/sass/overrides.sass';
```

**Comment by altynbek07** [comment]
@marcpaskell As a temporary solution, I did this:
In file `nuxt.config.js`:
```js
...
css: [
    // '~assets/scss/style.scss'
],
...
```

In file `layouts/default.vue`:
```js
...
<style lang="sass">
@import assets/scss/style.scss
</style>
```

**Comment by RensBoeser** [comment]
I tried this temporary solution and it worked for a while. As of late we tried to remove our seperate layouts and used only one: the `default.vue`. Now this temporary fix doesn't work anymore in dev, only in production builds.

**Comment by KareemDa** [comment]
Any updates on this issue ?

**Comment by HakimBhd** [comment]
You have to override sass variables and even style using `customVariables` option

file: `nuxt.config.js`
```javascript
...
buildModules: [
    ['@nuxtjs/vuetify',
      {
        ...
        treeShake: true,
        customVariables: ['~/assets/styles/vuetify/variables'],     
      }
    ],
]
```
enabling treeShake is important!

and then change variables or override style
file: `assets/styles/vuetify/variables/index.scss`
```scss
$body-font-family: 'Cairo';

.container {
  width: 100%;
  padding: 12px;
  margin-right: auto;
  margin-left: auto;
}

@import "~vuetify/src/styles/styles.sass";
```
