### ISSUE TITLE
Syntactically wrong css generation due to very old sass version

### ISSUE THREAD

**Issue by ibrahimBeladi** [nuxt-community/vuetify-module#520]
**Module version**
Latest

**Describe the bug**
There are some edge cases due to very old sass version

**To Reproduce**

1. Generate nuxt vuetify project
2. Add scss file that includes:
```scss
.f-grow-36 {
  flex: 0 0 36 * 2.083333333333% !important;
  max-width: 36 * 2.083333333333% !important;
}
```
3. Add that file in the nuxt configuration file, like: 
```js
css: ["~/assets/style/main.scss"],
```
5. Run npm run generate
6. Search for `74.%` without excluding the dist folder
7. Notice the result instead of having `75%` (as 36 * 2.083333333333% = 75%)

**Expected behavior**
Getting 75% (or at least 74% (without a dot), as it too broken)

**Additional context**
Related issue: https://github.com/sass/dart-sass/issues/2002
